### ISSUE TITLE
Windows/MSVC build fails: usearch `default-features = false` (v2.1.26+) disables `fp16lib`, triggering `#warning` -> fatal error C1021

### ISSUE THREAD

**Issue by randomnimbus** [samvallad33/vestige#93]
### Summary

Building the `vestige-mcp` crate on Windows with the MSVC toolchain fails while compiling the transitive `usearch` C++ sources. As of the v2.1.26 / v2.1.27 releases (and current `main`), `crates/vestige-core/Cargo.toml` pins the dependency as:

```toml
usearch = { version = "=2.23.0", default-features = false, optional = true }
```

`default-features = false` disables `usearch`'s default features, which are `["simsimd", "fp16lib"]`. With **both** disabled, `usearch`'s build script defines `USEARCH_USE_SIMSIMD=0` **and** `USEARCH_USE_FP16LIB=0`, which selects the bare half-precision fallback in `include/usearch/index_plugins.hpp`. That fallback's `#else` branch contains a C++ `#warning` directive:

```cpp
#warning "It's recommended to use SimSIMD and fp16lib for half-precision numerics"
```

MSVC's `cl.exe` treats `#warning` as a **fatal error** (`C1021`), so the build aborts.

### Environment

- OS: Windows 11
- Toolchain: `x86_64-pc-windows-msvc`, MSVC `cl.exe` 19.44 (VS 2022 17.14)
- `usearch` 2.23.0 (the exact pin in `vestige-core`)
- Reproduces on both v2.1.26 and v2.1.27 tags and on current `main`. v2.1.25 builds cleanly (it did not set `default-features = false`).

### Steps to reproduce

1. On Windows with the MSVC toolchain, check out v2.1.27 (or `main`).
2. From a Developer environment (vcvars), run a release build of the `vestige-mcp` crate (the failure is independent of the selected feature set; `usearch` is pulled in via the `vector-search` default feature).

### Error output

```
include\usearch/index_plugins.hpp(404): fatal error C1021: invalid preprocessor command 'warning'
error: failed to run custom build command for `usearch v2.23.0`
  process didn't exit successfully: `...\build\usearch-...\build-script-build` (exit code: 101)
```

### Root cause

The `default-features = false` pin was introduced to drop `usearch`'s SimSIMD AVX2/Haswell dispatch, which produces illegal-instruction crashes on older x86_64 CPUs (the class of failure tracked in #71). Disabling SimSIMD is the intended effect; however, `default-features = false` also drops `fp16lib`, which is an unrelated, self-contained scalar half-precision conversion library bundled with `usearch` (no SIMD intrinsics). With `fp16lib` off, the only remaining half-precision path is the bare `#else` branch that carries the `#warning`.

### Why it was not caught on GCC/Clang

GCC and Clang implement `#warning` as a non-fatal diagnostic, so the same code compiles (with a warning) on Linux and macOS. MSVC implements `#warning` as fatal `C1021`. Adding `/Zc:preprocessor` (the conforming preprocessor) does not change this — MSVC still rejects `#warning` with `C1021`.

### Suggested fix

Re-enable `fp16lib` only, keeping SimSIMD disabled, so the portability fix for older CPUs is preserved while the bare `#warning` path is avoided:

```toml
usearch = { version = "=2.23.0", default-features = false, features = ["fp16lib"], optional = true }
```

`fp16lib` is scalar (no SIMD intrinsics), so this does not reintroduce the illegal-instruction risk that motivated dropping the defaults. Alternatively, the bare `#warning` in `index_plugins.hpp` could be guarded behind a non-MSVC `cfg`, but that lives in `usearch` upstream; re-enabling `fp16lib` is a one-line change in `vestige-core` and restores the v2.1.25 behavior.

### Workaround

Applying the `features = ["fp16lib"]` change above to `crates/vestige-core/Cargo.toml` produces a clean MSVC build; verified building all three `vestige-mcp` binaries on the environment above.

**Comment by samvallad33** [comment]
Fixed in #94 — thank you for the exceptionally precise report; the diagnosis was correct in every detail and made this a one-line change.

**The fix** (`crates/vestige-core/Cargo.toml`), re-enabling `fp16lib` while keeping SimSIMD disabled:

```toml
usearch = { version = "=2.23.0", default-features = false, features = ["fp16lib"], optional = true }
```

I verified against the usearch 2.23.0 source that this is safe with respect to #71:
- usearch's `build.rs` sets `USEARCH_USE_FP16LIB=1` from the `fp16lib` feature alone; only the separate `simsimd` feature compiles `simsimd/c/lib.c` (the AVX2/Haswell dispatch behind the #71 illegal-instruction crash).
- So `fp16lib` selects the `#if USEARCH_USE_FP16LIB` branch in `index_plugins.hpp` (skipping the `#warning` that MSVC rejects as C1021) **without** reintroducing any SIMD intrinsics.

**Verification on macOS aarch64** (the C1021 is Windows/MSVC-only and can't be reproduced off-Windows):
- `cargo build -p vestige-core` and `-p vestige-mcp` ✅
- `cargo test -p vestige-core vector` → 9/9 pass
- `cargo clippy -p vestige-core` ✅ clean
- `cargo tree -e features` confirms `fp16lib` active and `simsimd` **not** active (so #71 stays fixed)
- `Cargo.lock` unchanged; usearch stays pinned at `=2.23.0`

Even though the change is minimal and doesn't introduce new behavior, the only host that can prove the MSVC build is green is Windows. **If you can pull `#94`'s branch (`fix/usearch-msvc-fp16lib-windows`) and confirm a clean MSVC build on your end, that would be the final confirmation** — you noted you already verified this exact change locally, so this should match.

And if for any reason this *doesn't* fully resolve the C1021 on your setup (or surfaces a different MSVC issue), please open a new issue/comment/PR here with the `cl.exe` output and your `cargo build -vv` log for the usearch compile step.

**Comment by randomnimbus** [comment]
Confirmed: a clean MSVC build of `main` (post-#94 merge, `9e1c386`) succeeds on Windows.

Environment:
- Windows 11, `x86_64-pc-windows-msvc`
- MSVC `cl.exe` 19.44 (VS 2022 17.14)
- CUDA build (`--features qwen3-embeddings,qwen3-reranker,cuda`)

To re-exercise the exact compile that previously failed, I force-cleaned the usearch artifacts (`cargo clean -p usearch --release`, 84 files removed) so usearch's C++ recompiled from scratch rather than serving from cache:

- `Compiling usearch v2.23.0` -> completed with no diagnostics
- Full release build of all three `vestige-mcp` binaries succeeded (`Finished`, ~1m50s)
- No `C1021`; binaries report `2.1.27`

This matches the change verified locally. The `default-features = false, features = ["fp16lib"]` pin builds clean on MSVC, and since simsimd remains disabled the #71 illegal-instruction fix is preserved.
